//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Dev/logical-motiv/libs/motiv-editor-react/src/lib/antlr/PropositionalLogic.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPropositionalLogicListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class PropositionalLogicBaseListener : IPropositionalLogicListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicParser.formula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormula([NotNull] PropositionalLogicParser.FormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicParser.formula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormula([NotNull] PropositionalLogicParser.FormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] PropositionalLogicParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] PropositionalLogicParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicParser.conditionalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalOrExpression([NotNull] PropositionalLogicParser.ConditionalOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicParser.conditionalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalOrExpression([NotNull] PropositionalLogicParser.ConditionalOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicParser.conditionalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalAndExpression([NotNull] PropositionalLogicParser.ConditionalAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicParser.conditionalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalAndExpression([NotNull] PropositionalLogicParser.ConditionalAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicParser.orExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOrExpression([NotNull] PropositionalLogicParser.OrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicParser.orExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOrExpression([NotNull] PropositionalLogicParser.OrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicParser.xorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXorExpression([NotNull] PropositionalLogicParser.XorExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicParser.xorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXorExpression([NotNull] PropositionalLogicParser.XorExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicParser.andExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpression([NotNull] PropositionalLogicParser.AndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicParser.andExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpression([NotNull] PropositionalLogicParser.AndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicParser.notExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpression([NotNull] PropositionalLogicParser.NotExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicParser.notExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpression([NotNull] PropositionalLogicParser.NotExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="PropositionalLogicParser.proposition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProposition([NotNull] PropositionalLogicParser.PropositionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="PropositionalLogicParser.proposition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProposition([NotNull] PropositionalLogicParser.PropositionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
